name = "faq-bot"
main = "src/index.mts"
compatibility_date = "2022-12-01"
kv_namespaces = [
    { binding = "server_config", id = ""}
]
[vars]
public_key = ""
# bot_token = ""
# Run `echo <VALUE> | wrangler secret put bot_token` to set this

[triggers]
crons = ["24 9 * * *"]
